### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by KpL00T** [teravice/MSF-ArchInstaller#1]
i try install whit this script. but i no undestand all code. (i no programmer)
but dont get working on my arch.

**Comment by qu-crypt** [comment]
I wrote this script 2 years+ ago.. Probably some packages have changed and some dependencies too. Needless to say you have to run this as root. Can you please provide the error you are seeing?

**Comment by kyberhajzl** [comment]
This script works, but problem is in line breaking. Every command must be in one line ;) I fork this project and repair broken lines.

**Comment by qu-crypt** [comment]
Thanks @kyberhajzl for spotting this. I have removed the extra lines. @Niil78 this should resolve your issues.
